source:
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded


# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: rouge


pagination:
  enabled: true
  per_page: 3
  permalink: "/page/:num/"

maps:
    google:
      api_key: AIzaSyCDglZFk0c0pH4LDgpwfuEbwa2tBZg4yJc

# SEO settings
title: Rabii Elbeji
description: "Personal website"
keywords: "rabii, elbeji, openbee, engineer"
url: https://rabi3elbeji.github.io
baseurl: ""

google_analytics: UA-115439306-1
repo: https://github.com/rabi3elbeji/rabi3elbeji.github.io

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    disqus_shortname: "rabi3elbeji"
    disqus_site_shortname: "rabi3elbeji"

# Author settings
author:
  name: Rabii Elbeji
  job: R&D Machine Learning Engineer
  bio: "Enthusiast performance, responsive design and usability, always looking for the best project and good coffee."
  thumb: /images/author.jpg
  qrcode: /images/qr-code.png
  email: rabi3elbeji@gmail.com
  url: https://rabi3elbeji.github.io
  github: https://github.com/rabi3elbeji
  twitter: https://twitter.com/rbelbeji
  linkedin: https://linkedin.com/in/rabii-elbeji-6432348a

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: blog
    title: Blog
  - slug: articles
    title: Articles
  - slug: books
    title: Books
  - slug: resume
    title: Resume

plugins: [jekyll-paginate-v2, jemoji, jekyll-toc]
exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
